trigger: none
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

extends:
  template: azure-pipelines/extension/stable.yml@templates
  parameters:
    publishExtension: true
    buildSteps:
      - bash: npm i -g npm@8.15.1
        displayName: Install npm@8.15.1

      - script: npm i
        displayName: Install dependencies

      - script: npm run build
        displayName: Compile
