name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft/vscode-engineering
      ref: main
      endpoint: Monaco

parameters:
  - name: publishPackage
    displayName: 🚀 Publish @vscode/jupyter-ipywidgets-
    type: boolean
    default: false

extends:
  template: azure-pipelines/npm-package/pipeline.yml@templates
  parameters:
    npmPackages:
      - name: jupyter-ipywidgets7
			  generateNotice: true
        testPlatforms: []

        buildSteps:
          - script: npm i
            displayName: Install dependencies

        publishPackage: ${{ parameters.publishPackage }}
